[package]
name = "your_project_name"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
macroquad = "0.3"
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
